version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_autronas
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: autronas
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_autronas
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DEFAULT_DATABASE: autronas
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: password
      ADMINER_DEFAULT_TYPE: postgres
      ADMINER_DESIGN: galkaev
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8080:8080
    volumes:
      - ./data/adminer:/var/www/html/plugins-enabled
